### ISSUE TITLE
NullPointerException when saving new incoming commits

### ISSUE THREAD

**Issue by KilianKrause** [adessoAG/coderadar#394]
Sometimes, when scanning and saving new commits, a `NullPointerException` is thrown in the `CommitAdapter`.
This can occur when the daterange of a project is set to something else than `null`.

```
Exception in thread "task-1" java.lang.NullPointerException
	at io.reflectoring.coderadar.graph.projectadministration.project.adapter.CommitAdapter.saveFileRenameRelationships(CommitAdapter.java:159)
	at io.reflectoring.coderadar.graph.projectadministration.project.adapter.CommitAdapter.saveCommitAndFileEntities(CommitAdapter.java:349)
	at io.reflectoring.coderadar.graph.projectadministration.project.adapter.CommitAdapter.addCommits(CommitAdapter.java:324)
	at io.reflectoring.coderadar.projectadministration.service.project.ScanProjectScheduler.checkForNewCommits(ScanProjectScheduler.java:177)
	at io.reflectoring.coderadar.projectadministration.service.project.ScanProjectScheduler.lambda$scheduleUpdateTask$0(ScanProjectScheduler.java:132)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:834)
```

**Comment by KilianKrause** [comment]
Unfortunately we are not able to reproduce this issue. @jo2 can you reproduce this one?
